"""empty message

Revision ID: 108928d5d91b
Revises: 
Create Date: 2021-06-14 16:48:10.146470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '108928d5d91b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subject_group')
    # ### end Alembic commands ###
