"""empty message

Revision ID: 5d05e8b6c666
Revises: dd6bfa541a7d
Create Date: 2021-07-12 19:21:12.025744

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5d05e8b6c666'
down_revision = 'dd6bfa541a7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'organisation_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_constraint('users_ibfk_1', 'users', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('users_ibfk_1', 'users', 'organisation', ['organisation_id'], ['id'])
    op.alter_column('users', 'organisation_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
