"""empty message

Revision ID: a0eedc7804ee
Revises: e80a268f94e4
Create Date: 2021-06-29 12:10:09.874448

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a0eedc7804ee'
down_revision = 'e80a268f94e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('node', 'sample_period',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.alter_column('node', 'average_period',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('node', 'average_period',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.alter_column('node', 'sample_period',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###
