"""empty message

Revision ID: cb475d4d984f
Revises: 8003717f51e5
Create Date: 2021-07-01 19:11:51.230852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb475d4d984f'
down_revision = '8003717f51e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_organisation_email', table_name='organisation')
    op.drop_index('name', table_name='organisation')
    op.drop_index('telephone', table_name='organisation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('telephone', 'organisation', ['telephone'], unique=False)
    op.create_index('name', 'organisation', ['name'], unique=False)
    op.create_index('ix_organisation_email', 'organisation', ['email'], unique=False)
    # ### end Alembic commands ###
